version: 2
updates:
  # Frontend npm dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      time: "04:00"           # Set a specific time for updates
      day: "monday"           # Set a specific day for consistency
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
    ignore:
      - dependency-name: "typescript"  # Example of ignoring specific dependencies
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"

  # Backend Maven dependencies
  - package-ecosystem: "maven"
    directory: "/backend"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      time: "05:00"
      day: "monday"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
    ignore:
      - dependency-name: "org.springframework:spring-boot" # Ignore Spring Boot if needed
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: "weekly"
      time: "06:00"
      day: "monday"
    commit-message:
      prefix: "deps"
      prefix-development: "dev-deps"
    labels:
      - "ci"
      - "dependencies"