services:
  fit-everywhere-be:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health || exit 1
      interval: 2s
      timeout: 30s
      retries: 200
      start_period: 10s

  fit-everywhere-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app  # Bind mount for development
      - /app/node_modules  # Bind mount for development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      fit-everywhere-be:
        condition: service_healthy

  fit-everywhere-proxy:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      fit-everywhere-be:
        condition: service_healthy
      fit-everywhere-fe:
        condition: service_started

volumes:
  backend_data: