services:
  fiteverywhere-db:
    image: mysql:8.0.39
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fiteverywhere_db
    ports:
      - "3306:3306"
    volumes:
      - db_file:/var/lib/mysql
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 30s
    networks:
      - backend

  fiteverywhere-be:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    depends_on:
      fiteverywhere-db:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - backend
      - frontend

  fiteverywhere-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app  # Bind mount for development
      - /app/node_modules  # Bind mount for development
    restart: on-failure
    networks:
      - frontend
    environment:
      - NODE_ENV=development
    depends_on:
      fiteverywhere-be:
        condition: service_started

volumes:
  backend_data:
  db_file:

networks:
  backend:
  frontend: