services:
  fit-everywhere-be:
    build: ./backend
    container_name: "fit-everywhere-be"
    environment:
      - SERVER_NAME=${SERVER_NAME}

  fit-everywhere-fe:
    build: ./frontend
    container_name: "fit-everywhere-fe"
    depends_on:
      - fit-everywhere-be

  fit-everywhere-proxy:
    build: ./nginx
    container_name: "fit-everywhere-proxy"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fit-everywhere-be
      - fit-everywhere-fe