services:
  fit-everywhere-be:
    build: ./backend
    container_name: "fit-everywhere-be"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiteverywhere-db.mysql.database.azure.com:3306/fiteverywhere_db?serverTimezone=UTC&useSSL=true&requireSSL=false
      SPRING_DATASOURCE_USERNAME: user_fiteverywhere
      SPRING_DATASOURCE_PASSWORD: F1t3v3rywh3r3.
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_OPEN_IN_VIEW: true
      
  fit-everywhere-fe:
    build: ./frontend
    container_name: "fit-everywhere-fe"
    volumes:
      - ./frontend:/app  # Bind mount to allow real-time changes
    depends_on:
      - fit-everywhere-be

  proxy:
    build: ./nginx
    container_name: "fit-everywhere-proxy"
    restart: always
    ports:
      - "80:80"

volumes:
  mysql_data: