services:
  fit-everywhere-be:
    build: ./backend
    container_name: "fit-everywhere-be"
    environment:
      - SERVER_NAME=http://fiteverywhere.me

  fit-everywhere-fe:
    build: ./frontend
    container_name: "fit-everywhere-fe"
    volumes:
      - ./frontend:/app  # Bind mount for development
    depends_on:
      - fit-everywhere-be

  fit-everywhere-proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: "fit-everywhere-proxy"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fit-everywhere-be
      - fit-everywhere-fe
