services:
  fiteverywhere-be:
    build: ./backend
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}

  fiteverywhere-fe:
    build: ./frontend
    depends_on:
      - fiteverywhere-be

  fiteverywhere-proxy:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fiteverywhere-be
      - fiteverywhere-fe