services:
  fit-everywhere-be:
    build: ./backend
    container_name: "fit-everywhere-be"
    environment:
      - SERVER_NAME=http://localhost

  fit-everywhere-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: "fit-everywhere-fe"
    volumes:
      - ./frontend:/app  # Bind mount for development
      - /app/node_modules  # Bind mount for development
    ports:
      - "3000:3000"
    depends_on:
      - fit-everywhere-be
    environment:
      - NODE_ENV=development

  fit-everywhere-proxy:
    build: ./nginx
    container_name: "fit-everywhere-proxy"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fit-everywhere-be
      - fit-everywhere-fe
