services:
  fit-everywhere-be:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - ./backend:/app
      - backend_data:/app/data
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  fit-everywhere-fe:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app  # Bind mount for development
      - /app/node_modules  # Bind mount for development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - fit-everywhere-be

  fit-everywhere-proxy:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fit-everywhere-be
      - fit-everywhere-fe

volumes:
  backend_data: