services:
  backend:
    build: ./backend
    container_name: "fit-everywhere-be"
      
  frontend:
    build: ./frontend
    container_name: "fit-everywhere-fe"
    volumes:
      - ./frontend:/app  # Bind mount to allow real-time changes
    depends_on:
      - backend

volumes:
  mysql_data:


 