services:
  fiteverywhere-be:
    build: ./backend
    environment:
      - SERVER_NAME=${SERVER_NAME}

  fiteverywhere-fe:
    build: ./frontend
    depends_on:
      - fiteverywhere-be

  fiteverywhere-proxy:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - fiteverywhere-be
      - fiteverywhere-fe