name: CD

concurrency:
  group: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
    steps:
      - uses: actions/checkout@v4

      - uses: azure/docker-login@v2
        with:
          login-server: fiteverywherecr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build \
          --platform linux/amd64 \
          --build-arg VITE_API_BASE_URL=${{ vars.API_URL }} \
          -t fiteverywherecr.azurecr.io/frontend:${{ github.ref_name }} \
          frontend/
          docker push fiteverywherecr.azurecr.io/frontend:${{ github.ref_name }}
          docker build \
          --platform linux/amd64 \
          --build-arg SPRING_PROFILES_ACTIVE=${{ github.ref_name }},general \
          --build-arg SPRING_DATASOURCE_URL="${{ secrets.DB_URL }}" \
          --build-arg SPRING_DATASOURCE_USERNAME=${{ secrets.DB_USERNAME }} \
          --build-arg SPRING_DATASOURCE_PASSWORD=${{ secrets.DB_PASSWORD }} \
          -t fiteverywherecr.azurecr.io/backend:${{ github.ref_name }} \
          backend/
          docker push fiteverywherecr.azurecr.io/backend:${{ github.ref_name }}

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      url: ${{ steps.deploy-frontend.outputs.webapp-url }}

    steps:
      - id: deploy-frontend
        uses: azure/webapps-deploy@v3.0.2
        with:
          app-name: ${{ vars.CLIENT_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          images: 'fiteverywherecr.azurecr.io/frontend:${{ github.ref_name }}'

      - uses: azure/webapps-deploy@v3.0.2
        with:
          app-name: ${{ vars.API_NAME }}
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_BACKEND }}
          images: 'fiteverywherecr.azurecr.io/backend:${{ github.ref_name }}'