name: CI

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: write

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Code Linting
        run: npm run lint
        working-directory: ./frontend

      - name: Coding Style Check
        run: npm run style-check
        working-directory: ./frontend

      - name: Build the project
        run: npm run build
        working-directory: ./frontend
  backend:
    runs-on: ubuntu-latest
    env:
      SERVER_NAME: http://fiteverywhere.me

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Clean and Compile with Maven
        run: mvn clean compile
        working-directory: ./backend

      - name: Code Style Check
        run: mvn checkstyle:check
        working-directory: ./backend

      - name: Unit and Integration Tests
        run: mvn verify jacoco:report
        working-directory: ./backend

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: ${{ github.workspace }}/backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 80
          min-coverage-changed-files: 60
          title: Code Coverage Report

      - name: Fail PR if overall coverage is less than 80%
        if: ${{ steps.jacoco.outputs.coverage-overall < 80.0 }}
        uses: actions/github-script@v6
        with:
          script: |
            core.setFailed('Overall coverage is less than 80%!')

      - name: Package the application
        run: mvn package -DskipTests
        working-directory: ./backend
