name: CI

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Code Linting
        run: npm run lint
        working-directory: ./frontend

      - name: Coding Style Check
        run: npm run style-check
        working-directory: ./frontend

      - name: Build the project
        run: npm run build
        working-directory: ./frontend
  backend:
    runs-on: ubuntu-latest
    env:
      SERVER_NAME: http://fiteverywhere.me

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Clean and Compile with Maven
        run: mvn clean compile
        working-directory: ./backend

      - name: Check Code Style and Validity
        run: mvn validate
        working-directory: ./backend

      - name: Run Backend Tests with Coverage
        run: mvn test
        working-directory: ./backend

      - name: Package the application
        run: mvn package
        working-directory: ./backend

      - name: Verify application quality criteria
        run: mvn verify
        working-directory: ./backend