name: CI

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: frontend

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npx playwright install
        working-directory: ./frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Code Linting
        run: npm run lint
        working-directory: ./frontend

      - name: Coding Style Check
        run: npm run style-check
        working-directory: ./frontend

      - name: Test with Coverage Vitest
        run: npm run coverage
        working-directory: ./frontend

      - name: Build the project
        run: npm run build
        working-directory: ./frontend
  backend:
    runs-on: ubuntu-latest
    env:
      CLIENT_ORIGIN: http://localhost
      SPRING_DATASOURCE_URL: jdbc:mysql://dbfiteverywhere.mysql.database.azure.com:3306/actions-fiteverywhere_db?useSSL=true
      SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: backend

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set .env file
        run: |
          cat <<EOF > .env
          CLIENT_ORIGIN=${{ env.CLIENT_ORIGIN }}
          SPRING_DATASOURCE_URL=${{ env.SPRING_DATASOURCE_URL }}
          SPRING_DATASOURCE_USERNAME=${{ env.SPRING_DATASOURCE_USERNAME }}
          SPRING_DATASOURCE_PASSWORD=${{ env.SPRING_DATASOURCE_PASSWORD }}
          EOF

      - name: Clean and Compile with Maven
        run: mvn clean compile
        working-directory: ./backend

      - name: Code Style Check
        run: mvn checkstyle:check
        working-directory: ./backend

      - name: Unit and Integration Tests
        run: mvn verify jacoco:report -Dspring.profiles.active=general
        working-directory: ./backend

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v5.1
        with:
          coverage_results_path: backend/target/site/jacoco/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 70
          fail_below_threshold: true
          publish_only_summary: true

      # Publish Coverage Job Summary  # Optional
      - name: Add Jacocoo report to workflow run summary
        run: |
          echo "| Outcome | Value |" >> $GITHUB_STEP_SUMMARY
          echo "| --- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| Code Coverage % | ${{ steps.jacoco_reporter.outputs.coverage_percentage }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :heavy_check_mark: Number of Lines Covered | ${{ steps.jacoco_reporter.outputs.covered_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| :x: Number of Lines Missed | ${{ steps.jacoco_reporter.outputs.missed_lines }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Total Number of Lines | ${{ steps.jacoco_reporter.outputs.total_lines }} |" >> $GITHUB_STEP_SUMMARY

      - name: Package the application
        run: mvn package -DskipTests -Dspring.profiles.active=general
        working-directory: ./backend
