name: Deploy to Azure VM

on:
  workflow_run:
      workflows: [FrontEnd Verification, Java CI with Maven]
      types:
        - completed
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
        
    - name: Copy files to Azure VM
      run: |
        scp -r -o StrictHostKeyChecking=no * fiteverywhereroot@4.210.226.23:~/FitEverywhere-T2E

    - name: SSH into VM and deploy
      run: |
        ssh -o StrictHostKeyChecking=no fiteverywhereroot@4.210.226.23 << 'EOF'
          cd ~/FitEverywhere-T2E
          sudo docker compose down      # Stop previous containers if any
          sudo docker compose up -d     # Start new containers
        EOF
