name: CI/CD for production

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Code Linting
        run: npm run lint
        working-directory: ./frontend

      - name: Coding Style Check
        run: npm run style-check
        working-directory: ./frontend

      - name: Build the project
        run: npm run build --if-present
        working-directory: ./frontend
  backend:
    runs-on: ubuntu-latest
    env:
      SPRING_DATASOURCE_URL: jdbc:mysql://fiteverywhere-db.mysql.database.azure.com:3306/fiteverywhere_db?serverTimezone=UTC&useSSL=true&requireSSL=false
      SPRING_DATASOURCE_USERNAME: user_fiteverywhere
      SPRING_DATASOURCE_PASSWORD: F1t3v3rywh3r3.
      SERVER_NAME: http://fiteverywhere.me

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Clean and Compile with Maven
        run: mvn clean compile
        working-directory: ./backend

      - name: Check Code Style and Validity
        run: mvn validate
        working-directory: ./backend

      - name: Run Backend Tests with Coverage
        run: mvn test jacoco:report
        working-directory: ./backend

      - name: Package the application
        run: mvn package
        working-directory: ./backend

      - name: Verify application quality criteria
        run: mvn verify
        working-directory: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: [ backend, frontend ]
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Clean and Copy files to Azure VM
        run: |
          ssh -o StrictHostKeyChecking=no fiteverywhereroot@4.210.226.23 "rm -rf ~/FitEverywhere-T2E/*"
          scp -r -o StrictHostKeyChecking=no * fiteverywhereroot@4.210.226.23:~/FitEverywhere-T2E

      - name: SSH into VM and deploy
        env:
          SERVER_NAME: http://fiteverywhere.me
        run: |
          ssh -o StrictHostKeyChecking=no fiteverywhereroot@4.210.226.23 << 'EOF'
          
            cd ~/FitEverywhere-T2E
            sudo docker stop $(sudo docker ps -a -q)      # Stop previous containers if any
            sudo docker rm $(sudo docker ps -a -q)        # Remove previous containers if any
            sudo docker rmi $(sudo docker images -a -q)
            sudo docker compose -f docker-compose.yml up -d    # Start new containers
          EOF
